# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-02 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20160302_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='adress',
            new_name='address',
        ),
    ]
